version: "3"

services:
    python_app:
      build:
        context: ./PythonApp
        dockerfile: Dockerfile
      depends_on:
        - mongo_db

    mongo_db:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db

volumes:
    mongo_data: